spring:
  application:
    name: module-initialization
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        # Format queries
        format_sql: true
  datasource:
    # URL connection to database (spring-security is database name)
    url: jdbc:h2:mem:spring-security
    # H2 sql Driver
    driver-class-name: org.h2.Driver
    username: root
    password: 12345
    h2:
      console:
        enabled: true